export const TYPOGRAPHY_TOKENS = {
  lineHeight: {
    "025": "14px",
    "050": "18px",
    "075": "22px",
    "100": "24px",
    "200": "26px",
    "300": "30px",
    "400": "36px",
    "500": "48px",
    "600": "56px",
    "700": "62px",
    "800": "84px",
    "900": "104px",
    "1000": "156px",
  },
  letterSpacing: {
    "000": "0",
    "100": "-0.1px",
    "200": "-0.2px",
    "300": "-0.3px",
    "400": "-0.4px",
  },
  fontSize: {
    "025": "10px",
    "050": "12px",
    "075": "14px",
    "100": "16px",
    "200": "18px",
    "300": "20px",
    "400": "24px",
    "500": "32px",
    "600": "38px",
    "700": "48px",
    "800": "64px",
    "900": "80px",
    "1000": "120px",
  },
  fontWeight: {
    400: "400",
    500: "500",
    700: "700",
    800: "800",
  },
};

export const TYPOGRAPHY_VARIANTS = {
  display1: {
    lineHeight: TYPOGRAPHY_TOKENS.lineHeight["1000"],
    letterSpacing: TYPOGRAPHY_TOKENS.letterSpacing["400"],
    fontSize: TYPOGRAPHY_TOKENS.fontSize["1000"],
    fontWeight: TYPOGRAPHY_TOKENS.fontWeight[800],
  },
  display2: {
    lineHeight: TYPOGRAPHY_TOKENS.lineHeight["900"],
    letterSpacing: TYPOGRAPHY_TOKENS.letterSpacing["400"],
    fontSize: TYPOGRAPHY_TOKENS.fontSize["900"],
    fontWeight: TYPOGRAPHY_TOKENS.fontWeight[800],
  },
  display3: {
    lineHeight: TYPOGRAPHY_TOKENS.lineHeight["800"],
    letterSpacing: TYPOGRAPHY_TOKENS.letterSpacing["400"],
    fontSize: TYPOGRAPHY_TOKENS.fontSize["800"],
    fontWeight: TYPOGRAPHY_TOKENS.fontWeight[800],
  },
  display4: {
    lineHeight: TYPOGRAPHY_TOKENS.lineHeight["700"],
    letterSpacing: TYPOGRAPHY_TOKENS.letterSpacing["400"],
    fontSize: TYPOGRAPHY_TOKENS.fontSize["700"],
    fontWeight: TYPOGRAPHY_TOKENS.fontWeight[800],
  },
  heading1: {
    lineHeight: TYPOGRAPHY_TOKENS.lineHeight["600"],
    letterSpacing: TYPOGRAPHY_TOKENS.letterSpacing["400"],
    fontSize: TYPOGRAPHY_TOKENS.fontSize["600"],
    fontWeight: TYPOGRAPHY_TOKENS.fontWeight[700],
  },
  heading2: {
    lineHeight: TYPOGRAPHY_TOKENS.lineHeight["500"],
    letterSpacing: TYPOGRAPHY_TOKENS.letterSpacing["400"],
    fontSize: TYPOGRAPHY_TOKENS.fontSize["500"],
    fontWeight: TYPOGRAPHY_TOKENS.fontWeight[700],
  },
  heading3: {
    lineHeight: TYPOGRAPHY_TOKENS.lineHeight["400"],
    letterSpacing: TYPOGRAPHY_TOKENS.letterSpacing["300"],
    fontSize: TYPOGRAPHY_TOKENS.fontSize["400"],
    fontWeight: TYPOGRAPHY_TOKENS.fontWeight[700],
  },
  heading4: {
    lineHeight: TYPOGRAPHY_TOKENS.lineHeight["300"],
    letterSpacing: TYPOGRAPHY_TOKENS.letterSpacing["200"],
    fontSize: TYPOGRAPHY_TOKENS.fontSize["300"],
    fontWeight: TYPOGRAPHY_TOKENS.fontWeight[700],
  },
  heading5: {
    lineHeight: TYPOGRAPHY_TOKENS.lineHeight["200"],
    letterSpacing: TYPOGRAPHY_TOKENS.letterSpacing["100"],
    fontSize: TYPOGRAPHY_TOKENS.fontSize["200"],
    fontWeight: TYPOGRAPHY_TOKENS.fontWeight[700],
  },
  heading6: {
    lineHeight: TYPOGRAPHY_TOKENS.lineHeight["100"],
    letterSpacing: TYPOGRAPHY_TOKENS.letterSpacing["100"],
    fontSize: TYPOGRAPHY_TOKENS.fontSize["100"],
    fontWeight: TYPOGRAPHY_TOKENS.fontWeight[500],
  },
  subtitle1: {
    lineHeight: TYPOGRAPHY_TOKENS.lineHeight["075"],
    letterSpacing: TYPOGRAPHY_TOKENS.letterSpacing["100"],
    fontSize: TYPOGRAPHY_TOKENS.fontSize["075"],
    fontWeight: TYPOGRAPHY_TOKENS.fontWeight[500],
  },
  subtitle2: {
    lineHeight: TYPOGRAPHY_TOKENS.lineHeight["050"],
    letterSpacing: TYPOGRAPHY_TOKENS.letterSpacing["000"],
    fontSize: TYPOGRAPHY_TOKENS.fontSize["050"],
    fontWeight: TYPOGRAPHY_TOKENS.fontWeight[500],
  },
  body1: {
    lineHeight: TYPOGRAPHY_TOKENS.lineHeight["100"],
    letterSpacing: TYPOGRAPHY_TOKENS.letterSpacing["100"],
    fontSize: TYPOGRAPHY_TOKENS.fontSize["100"],
    fontWeight: TYPOGRAPHY_TOKENS.fontWeight[400],
  },
  body2: {
    lineHeight: TYPOGRAPHY_TOKENS.lineHeight["075"],
    letterSpacing: TYPOGRAPHY_TOKENS.letterSpacing["100"],
    fontSize: TYPOGRAPHY_TOKENS.fontSize["075"],
    fontWeight: TYPOGRAPHY_TOKENS.fontWeight[400],
  },
  body3: {
    lineHeight: TYPOGRAPHY_TOKENS.lineHeight["050"],
    letterSpacing: TYPOGRAPHY_TOKENS.letterSpacing["100"],
    fontSize: TYPOGRAPHY_TOKENS.fontSize["050"],
    fontWeight: TYPOGRAPHY_TOKENS.fontWeight[400],
  },
  body4: {
    lineHeight: TYPOGRAPHY_TOKENS.lineHeight["025"],
    letterSpacing: TYPOGRAPHY_TOKENS.letterSpacing["000"],
    fontSize: TYPOGRAPHY_TOKENS.fontSize["025"],
    fontWeight: TYPOGRAPHY_TOKENS.fontWeight[400],
  },
  code1: {
    lineHeight: TYPOGRAPHY_TOKENS.lineHeight["075"],
    letterSpacing: TYPOGRAPHY_TOKENS.letterSpacing["000"],
    fontSize: TYPOGRAPHY_TOKENS.fontSize["075"],
    fontWeight: TYPOGRAPHY_TOKENS.fontWeight[400],
  },
  code2: {
    lineHeight: TYPOGRAPHY_TOKENS.lineHeight["050"],
    letterSpacing: TYPOGRAPHY_TOKENS.letterSpacing["000"],
    fontSize: TYPOGRAPHY_TOKENS.fontSize["050"],
    fontWeight: TYPOGRAPHY_TOKENS.fontWeight[400],
  },
};
